Correct filename case in #include directive
On a filename case-sensitive operating system like Linux, use of the incorrect filename case in an #include directive causes compilation to fail:

/tmp/774189247/custom/wavesharesharpdustsensor/WaveshareSharpDustSensor.h:7:22: fatal error: arduino.h: No such file or directory

#include "arduino.h"